version: 2.1

jobs: 
  validate_terraform:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Initialize and plan Terraform (check plan out here before approving!)
          command: |
            #Load CIRCLE  environment variables as bash environment variables
            . "${BASH_ENV}"
            cd example && terraform init && terraform validate

workflows:
  version: 2.1
  validate_terraform_changes:
    jobs:
      - validate_terraform